initial

diff --git a/.github/workflows/pars-cli.yml b/.github/workflows/pars-cli.yml
--- a/.github/workflows/pars-cli.yml
+++ b/.github/workflows/pars-cli.yml
@@ -192,6 +192,26 @@ jobs:
           TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
           echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
 
+
+
+      - name: Clone Downloads Repository
+        run: |
+          git clone https://github.com/parsdevkit/downloads.git
+
+
+      - name: Read Changelog File
+        id: changelog
+        run: |
+          changelog_file="contents/en/pars/changelogs/${{ env.tag_name }}.md"
+          if [ -f "$changelog_file" ]; then
+            content=$(cat "$changelog_file")
+            echo "changelog_content=$content" >> $GITHUB_ENV
+          else
+            echo "Changelog file not found for tag $tag"
+            exit 1
+          fi
+
+
       - name: Create GitHub Release
         id: create_release
         uses: actions/create-release@v1
@@ -200,7 +220,7 @@ jobs:
         with:
           tag_name: ${{ env.tag_name }}
           release_name: Release ${{ env.tag_name }}
-          body: "test"
+          body: ${{ env.changelog_content }}
           draft: false
           prerelease: false
 
